source 'https://rubygems.org'

gem 'rails', '4.1.0.rc1'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'pry'
gem 'jquery-rails'
gem 'spring'
gem 'rspec', '~> 2.0'
gem 'rspec-rails', '~> 2.0'
gem 'capybara', '~> 2.1.0'
gem 'simple_form'
gem 'binding_of_caller'
gem 'better_errors'
gem 'nested_form'
gem 'timecop'
gem 'factory_girl_rails'
